// Generates SQL INSERT for Supabase SQL editor
const USER_ID = '236d46a0-53a4-40ac-862a-b3746cf34977';
let id = 1700000000000;
const nextId = () => String(id += 1000);

const books = [
  // 2026
  { y:'2026', t:'All the Knowledge in the World', a:'Simon Garfield', g:'Non-Fiction' },
  // 2025
  { y:'2025', t:'One Ordinary Guy', a:'Steve Versce', g:'Biography' },
  { y:'2025', t:'Hyperion', a:'Dan Simmons', g:'Sci-Fi' },
  { y:'2025', t:'Roverandom', a:'J. R. R. Tolkien', g:'Fantasy' },
  { y:'2025', t:'The Maine Lobster Book', a:'Virginia Wright', g:'Non-Fiction' },
  { y:'2025', t:'Cabin', a:'Patrick Hutchison', g:'Non-Fiction' },
  // 2024
  { y:'2024', t:'The Last Storyteller', a:'Frank Delaney', g:'Fiction' },
  // 2023
  { y:'2023', t:"Preppers Long-Term Survival Guide", a:'Jim Cobb', g:'Non-Fiction' },
  { y:'2023', t:"Abe Lincoln's Anecdotes & Stories", a:'R. D. Wordsworth', g:'History' },
  { y:'2023', t:"Lincoln's Speeches", a:'Caleb Brown', g:'History' },
  { y:'2023', t:'Stiff', a:'Mary Roach', g:'Non-Fiction' },
  // 2022
  { y:'2022', t:'Words of Radiance', a:'Brandon Sanderson', g:'Fantasy' },
  { y:'2022', t:'1491', a:'Charles C. Mann', g:'History' },
  { y:'2022', t:'The Splendid & the Vile', a:'Erik Larson', g:'History' },
  { y:'2022', t:'The Way of Kings', a:'Brandon Sanderson', g:'Fantasy' },
  // 2021
  { y:'2021', t:'A World Undone', a:'G. J. Meyer', g:'History' },
  { y:'2021', t:'A Little History of the World', a:'E. H. Gombrich', g:'History' },
  { y:'2021', t:'The End is Always Near', a:'Dan Carlin', g:'Non-Fiction' },
  { y:'2021', t:'Kindred: Neanderthal Life, Love, Death and Art', a:'Rebecca Wragg Sykes', g:'Non-Fiction' },
  { y:'2021', t:'Nineveh: History & Legacy of the Assyrian Capital', a:'', g:'History' },
  { y:'2021', t:'History of the Ancient World', a:'Susan Wise Bauer', g:'History' },
  // 2020
  { y:'2020', t:'The Horse, the Wheel, and Language', a:'David Anthony', g:'History' },
  { y:'2020', t:'The Sirens of Titan', a:'Kurt Vonnegut', g:'Sci-Fi' },
  { y:'2020', t:'Guns, Germs, and Steel', a:'Jared Diamond', g:'Non-Fiction' },
  { y:'2020', t:'The Brothers Karamazov', a:'Fyodor Dostoevsky', g:'Fiction' },
  // 2019
  { y:'2019', t:'America Before', a:'Graham Hancock', g:'Non-Fiction' },
  { y:'2019', t:'Fifty Ways to Look at Winston Churchill', a:'Gretchen Rubin', g:'Biography' },
  { y:'2019', t:'Sapiens', a:'Yuval Noah Harari', g:'Non-Fiction' },
  { y:'2019', t:'The Last Crossing', a:'Guy Vanderhaeghe', g:'Historical Fiction' },
  { y:'2019', t:'The Storm Before the Storm', a:'Mike Duncan', g:'History' },
  // 2018
  { y:'2018', t:'Ireland', a:'Frank Delaney', g:'Historical Fiction' },
  { y:'2018', t:'London', a:'Edward Rutherfurd', g:'Historical Fiction' },
  { y:'2018', t:'Sayonara', a:'James Michener', g:'Historical Fiction' },
  { y:'2018', t:'Go Wild', a:'John J. Ratey & Richard Manning', g:'Non-Fiction' },
  { y:'2018', t:'The Seven Daughters of Eve', a:'Bryan Sykes', g:'Non-Fiction' },
  // 2017
  { y:'2017', t:'The Princes of Ireland', a:'Edward Rutherfurd', g:'Historical Fiction' },
  { y:'2017', t:'The Journey of Man', a:'Spencer Wells', g:'Non-Fiction' },
  { y:'2017', t:'Saxons, Vikings, and Celts', a:'Bryan Sykes', g:'History' },
  { y:'2017', t:'Space', a:'James Michener', g:'Historical Fiction' },
  { y:'2017', t:'The Great Bridge', a:'David McCullough', g:'History' },
  { y:'2017', t:'Unlocking the Past', a:'Martin Jones', g:'Non-Fiction' },
  { y:'2017', t:'Archaeology and Language', a:'Colin Renfrew', g:'History' },
  { y:'2017', t:'Europe Between the Oceans', a:'Barry Cunliffe', g:'History' },
  { y:'2017', t:'Tribes', a:'Seth Godin', g:'Non-Fiction' },
  // 2016
  { y:'2016', t:'The Drifters', a:'James Michener', g:'Fiction' },
  { y:'2016', t:'The Big Fat Surprise', a:'Nina Teicholz', g:'Non-Fiction' },
  { y:'2016', t:'The Bridges at Toko-Ri', a:'James Michener', g:'Historical Fiction' },
  { y:'2016', t:'Redemption', a:'Leon Uris', g:'Historical Fiction' },
  { y:'2016', t:'Ancient History: 3000 BC to 476 AD', a:'George Rawlinson', g:'History' },
  { y:'2016', t:'A History of Ancient Britain', a:'Neil Oliver', g:'History' },
  { y:'2016', t:'Cro-Magnon', a:'Brian Fagan', g:'Non-Fiction' },
  // 2015
  { y:'2015', t:'The Third Chimpanzee', a:'Jared Diamond', g:'Non-Fiction' },
  { y:'2015', t:'The Wake', a:'Paul Kingsnorth', g:'Historical Fiction' },
  { y:'2015', t:'Everyday Life in Prehistoric Times', a:'C. H. B. Quennell', g:'History' },
  { y:'2015', t:'1177 BC: The Year Civilization Collapsed', a:'Eric Cline', g:'History' },
  { y:'2015', t:'Exodus', a:'Leon Uris', g:'Historical Fiction' },
  { y:'2015', t:'Ireland: A Terrible Beauty', a:'Leon Uris', g:'Non-Fiction' },
  { y:'2015', t:'After the Ice', a:'Steven Mithen', g:'History' },
  { y:'2015', t:'Atlantis Blueprint', a:'Colin Wilson', g:'Non-Fiction' },
  // 2014
  { y:'2014', t:'The Imperial Cruise', a:'James Bradley', g:'History' },
  { y:'2014', t:'Bunker Hill', a:'Nathaniel Philbrick', g:'History' },
  { y:'2014', t:'Trinity', a:'Leon Uris', g:'Historical Fiction' },
  { y:'2014', t:'Bard: An Irish History', a:'Morgan Llywelyn', g:'Historical Fiction' },
  { y:'2014', t:'Chesapeake', a:'James Michener', g:'Historical Fiction' },
  { y:'2014', t:'Journey', a:'James Michener', g:'Historical Fiction' },
  { y:'2014', t:'Food of the Gods', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'In the Days of the Comet', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'The War of the Worlds', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'The First Men in the Moon', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'The Island of Doctor Moreau', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'The Invisible Man', a:'H. G. Wells', g:'Sci-Fi' },
  { y:'2014', t:'The Time Machine', a:'H. G. Wells', g:'Sci-Fi' },
  // 2013
  { y:'2013', t:'Caravans', a:'James Michener', g:'Historical Fiction' },
  { y:'2013', t:'Unbroken', a:'Laura Hillenbrand', g:'Non-Fiction' },
  { y:'2013', t:'Iberia', a:'James Michener', g:'Historical Fiction' },
  { y:'2013', t:'Inferno', a:'Dan Brown', g:'Thriller' },
  { y:'2013', t:'A Dance with Dragons', a:'George R. R. Martin', g:'Fantasy' },
  { y:'2013', t:'A Feast for Crows', a:'George R. R. Martin', g:'Fantasy' },
  { y:'2013', t:'A Storm of Swords', a:'George R. R. Martin', g:'Fantasy' },
  // 2012
  { y:'2012', t:'A Clash of Kings', a:'George R. R. Martin', g:'Fantasy' },
  { y:'2012', t:'A Game of Thrones', a:'George R. R. Martin', g:'Fantasy' },
  { y:'2012', t:'Mexico', a:'James Michener', g:'Historical Fiction' },
  { y:'2012', t:'The 500', a:'Matthew Quirk', g:'Thriller' },
  { y:'2012', t:'The Covenant', a:'James Michener', g:'Historical Fiction' },
  { y:'2012', t:'A Walk in the Woods', a:'Bill Bryson', g:'Non-Fiction' },
  // 2011
  { y:'2011', t:'Texas', a:'James Michener', g:'Historical Fiction' },
  { y:'2011', t:'Poland', a:'James Michener', g:'Historical Fiction' },
  { y:'2011', t:'The Source', a:'James Michener', g:'Historical Fiction' },
  { y:'2011', t:'1000 Events That Shaped the World', a:'National Geographic', g:'History' },
  // 2010
  { y:'2010', t:'The Vikings', a:'Robert Ferguson', g:'History' },
  { y:'2010', t:'Alaska', a:'James Michener', g:'Historical Fiction' },
  { y:'2010', t:'The Silkie', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:'2010', t:'Cahokia', a:'Timothy Pauketat', g:'History' },
  { y:'2010', t:'Andrew Jackson', a:'Jon Meacham', g:'Biography' },
  { y:'2010', t:'The Winter King', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2010', t:'The Lost Symbol', a:'Dan Brown', g:'Thriller' },
  // 2009
  { y:'2009', t:'Gallows Thief', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2009', t:'Gone with the Wind', a:'Margaret Mitchell', g:'Historical Fiction' },
  { y:'2009', t:'Team of Rivals', a:'Doris Kearns Goodwin', g:'History' },
  { y:'2009', t:'Harry Potter and the Deathly Hallows', a:'J. K. Rowling', g:'Fantasy' },
  { y:'2009', t:'Harry Potter and the Half-Blood Prince', a:'J. K. Rowling', g:'Fantasy' },
  { y:'2009', t:'Harry Potter and the Order of the Phoenix', a:'J. K. Rowling', g:'Fantasy' },
  { y:'2009', t:'Harry Potter and the Goblet of Fire', a:'J. K. Rowling', g:'Fantasy' },
  { y:'2009', t:'Harry Potter and the Prisoner of Azkaban', a:'J. K. Rowling', g:'Fantasy' },
  // 2008
  { y:'2008', t:'Harry Potter and the Chamber of Secrets', a:'J. K. Rowling', g:'Fantasy' },
  { y:'2008', t:"Harry Potter and the Sorcerer's Stone", a:'J. K. Rowling', g:'Fantasy' },
  { y:'2008', t:'The Dark Tower', a:'Stephen King', g:'Horror' },
  { y:'2008', t:'The Last Templar', a:'Raymond Khoury', g:'Thriller' },
  { y:'2008', t:'Nothing Like It in the World', a:'Stephen Ambrose', g:'History' },
  { y:'2008', t:'The Stand', a:'Stephen King', g:'Horror' },
  { y:'2008', t:'Stone by Stone', a:'Robert Thorson', g:'Non-Fiction' },
  { y:'2008', t:'Lords of the North', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2008', t:'By Order of the President', a:'W.E.B. Griffin', g:'Thriller' },
  // 2007
  { y:'2007', t:'Vagabond', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2007', t:"Harlequin (The Archer's Tale)", a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2007', t:'The Mayflower', a:'Nathaniel Philbrick', g:'History' },
  { y:'2007', t:'Deception Point', a:'Dan Brown', g:'Thriller' },
  { y:'2007', t:'Cod', a:'Mark Kurlansky', g:'Non-Fiction' },
  { y:'2007', t:'Stonehenge', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2007', t:'If Those Trees Could Talk', a:'Frank Tracey', g:'History' },
  { y:'2007', t:'Scotland', a:'Jenny Wormald', g:'History' },
  { y:'2007', t:'Digital Fortress', a:'Dan Brown', g:'Thriller' },
  { y:'2007', t:'The Pale Horseman', a:'Bernard Cornwell', g:'Historical Fiction' },
  { y:'2007', t:'The Last Kingdom', a:'Bernard Cornwell', g:'Historical Fiction' },
  // 2006
  { y:'2006', t:'1776', a:'David McCullough', g:'History' },
  { y:'2006', t:'The City of Falling Angels', a:'John Berendt', g:'Non-Fiction' },
  { y:'2006', t:'Paganism and Christianity in the 4th-8th Centuries', a:'Ramsay MacMullen', g:'History' },
  { y:'2006', t:'The Risk Pool', a:'Richard Russo', g:'Fiction' },
  { y:'2006', t:'A Princess of Mars', a:'Edgar Rice Burroughs', g:'Sci-Fi' },
  { y:'2006', t:'Angels & Demons', a:'Dan Brown', g:'Thriller' },
  { y:'2006', t:'Benjamin Franklin', a:'Walter Isaacson', g:'Biography' },
  { y:'2006', t:'Caribbean', a:'James Michener', g:'Historical Fiction' },
  // 2005
  { y:'2005', t:'Robinson Crusoe', a:'Daniel Defoe', g:'Fiction' },
  { y:'2005', t:'The Human Story', a:'James C. Davis', g:'History' },
  { y:'2005', t:'John Adams', a:'David McCullough', g:'Biography' },
  { y:'2005', t:'The Da Vinci Code', a:'Dan Brown', g:'Thriller' },
  // 2004
  { y:'2004', t:'The Greatest Generation Speaks', a:'Tom Brokaw', g:'Non-Fiction' },
  { y:'2004', t:'Napoleon Bonaparte', a:'Alan Schom', g:'Biography' },
  { y:'2004', t:'Galtees Anthology', a:'', g:'History' },
  { y:'2004', t:'White Knights Dark Earls', a:'John Gallahue', g:'History' },
  // 2003
  { y:'2003', t:'Salt', a:'Mark Kurlansky', g:'Non-Fiction' },
  { y:'2003', t:'Mapping Human History', a:'Steve Olson', g:'Non-Fiction' },
  { y:'2003', t:'Oxford History of Britain', a:'Kenneth O. Morgan', g:'History' },
  { y:'2003', t:'The Botany of Desire', a:'Michael Pollan', g:'Non-Fiction' },
  // 2002
  { y:'2002', t:'Undaunted Courage', a:'Stephen Ambrose', g:'History' },
  { y:'2002', t:'Left Behind', a:'Tim LaHaye & Jerry Jenkins', g:'Fiction' },
  { y:'2002', t:"Angela's Ashes", a:'Frank McCourt', g:'Non-Fiction' },
  { y:'2002', t:'A Year in the Maine Woods', a:'Bernd Heinrich', g:'Non-Fiction' },
  // 1996
  { y:'1996', t:'The Celestine Prophecy', a:'James Redfield', g:'Fiction' },
  // No year
  { y:null, t:'Kill Devil Hill', a:'Harry Combs', g:'History' },
  { y:null, t:'The Killer Angels', a:'Michael Shaara', g:'Historical Fiction' },
  { y:null, t:'Abraham Lincoln', a:'William Safire', g:'Biography' },
  { y:null, t:'QB VII', a:'Leon Uris', g:'Historical Fiction' },
  { y:null, t:'Bird', a:'Larry Bird & Bob Ryan', g:'Biography' },
  { y:null, t:'Papillon', a:'Henri Charrière', g:'Non-Fiction' },
  { y:null, t:'Dear Bess', a:'Harry S. Truman', g:'Biography' },
  { y:null, t:'Roots', a:'Alex Haley', g:'Historical Fiction' },
  { y:null, t:'The Name of War', a:'Jill Lepore', g:'History' },
  { y:null, t:'The Hot House', a:'Pete Earley', g:'Non-Fiction' },
  { y:null, t:'Andersonville', a:'John McElroy', g:'Historical Fiction' },
  { y:null, t:'The Rise and Fall of the Third Reich', a:'William L. Shirer', g:'History' },
  { y:null, t:'Clan of the Cave Bear', a:'Jean Auel', g:'Historical Fiction' },
  { y:null, t:'The Plains of Passage', a:'Jean Auel', g:'Historical Fiction' },
  { y:null, t:'The Teachings of Don Juan', a:'Carlos Castaneda', g:'Non-Fiction' },
  { y:null, t:'If the South Had Won the Civil War', a:'MacKinlay Kantor', g:'Fiction' },
  { y:null, t:'The Prophet', a:'Kahlil Gibran', g:'Non-Fiction' },
  { y:null, t:'A Separate Reality', a:'Carlos Castaneda', g:'Non-Fiction' },
  { y:null, t:'Centennial', a:'James Michener', g:'Historical Fiction' },
  { y:null, t:'Hawaii', a:'James Michener', g:'Historical Fiction' },
  { y:null, t:'Coma', a:'Robin Cook', g:'Thriller' },
  { y:null, t:'Helter Skelter', a:'Vincent Bugliosi & Curt Gentry', g:'Non-Fiction' },
  { y:null, t:'Against the Fall of Night', a:'Arthur C. Clarke', g:'Sci-Fi' },
  { y:null, t:'The City and the Stars', a:'Arthur C. Clarke', g:'Sci-Fi' },
  { y:null, t:'Watership Down', a:'Richard Adams', g:'Fiction' },
  { y:null, t:'Tinker, Tailor, Soldier, Spy', a:'John le Carré', g:'Thriller' },
  { y:null, t:'The Hunt for Red October', a:'Tom Clancy', g:'Thriller' },
  { y:null, t:'The Firm', a:'John Grisham', g:'Thriller' },
  { y:null, t:'The Pelican Brief', a:'John Grisham', g:'Thriller' },
  { y:null, t:'A Time to Kill', a:'John Grisham', g:'Thriller' },
  { y:null, t:'Looking Backward', a:'Edward Bellamy', g:'Fiction' },
  { y:null, t:'Kon-Tiki', a:'Thor Heyerdahl', g:'Non-Fiction' },
  { y:null, t:'The Other', a:'Thomas Tryon', g:'Horror' },
  { y:null, t:'Bury My Heart at Wounded Knee', a:'Dee Brown', g:'History' },
  { y:null, t:'Foundation', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'Foundation and Empire', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'Second Foundation', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'The Stainless Steel Rat', a:'Harry Harrison', g:'Sci-Fi' },
  { y:null, t:'The Caves of Steel', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'I, Robot', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'Fantastic Voyage', a:'Isaac Asimov', g:'Sci-Fi' },
  { y:null, t:'Weapon Shops of Isher', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'Fahrenheit 451', a:'Ray Bradbury', g:'Sci-Fi' },
  { y:null, t:'Slaughterhouse-Five', a:'Kurt Vonnegut', g:'Sci-Fi' },
  { y:null, t:'The Andromeda Strain', a:'Michael Crichton', g:'Sci-Fi' },
  { y:null, t:'Animal Farm', a:'George Orwell', g:'Fiction' },
  { y:null, t:'1984', a:'George Orwell', g:'Sci-Fi' },
  { y:null, t:'Tarzan of the Apes', a:'Edgar Rice Burroughs', g:'Fiction' },
  { y:null, t:'Tarzan and Jane', a:'Edgar Rice Burroughs', g:'Fiction' },
  { y:null, t:'Princess of Mars', a:'Edgar Rice Burroughs', g:'Sci-Fi' },
  { y:null, t:'The Hobbit', a:'J. R. R. Tolkien', g:'Fantasy' },
  { y:null, t:'The Fellowship of the Ring', a:'J. R. R. Tolkien', g:'Fantasy' },
  { y:null, t:'The Two Towers', a:'J. R. R. Tolkien', g:'Fantasy' },
  { y:null, t:'The Return of the King', a:'J. R. R. Tolkien', g:'Fantasy' },
  { y:null, t:'The Call of the Wild', a:'Jack London', g:'Fiction' },
  { y:null, t:'The Sleeping Prophet', a:'Edgar Cayce', g:'Non-Fiction' },
  { y:null, t:'Many Mansions', a:'Gina Cerminara', g:'Non-Fiction' },
  { y:null, t:'Old Yeller', a:'Fred Gipson', g:'Fiction' },
  { y:null, t:'Inherit the Wind', a:'Jerome Lawrence & Robert E. Lee', g:'Fiction' },
  { y:null, t:'To Kill a Mockingbird', a:'Harper Lee', g:'Fiction' },
  { y:null, t:'Vietnam: A History', a:'Stanley Karnow', g:'History' },
  { y:null, t:'The Wasp', a:'Eric Frank Russell', g:'Sci-Fi' },
  { y:null, t:'David Copperfield', a:'Charles Dickens', g:'Fiction' },
  { y:null, t:"Gulliver's Travels", a:'Jonathan Swift', g:'Fiction' },
  { y:null, t:'Replay', a:'Ken Grimwood', g:'Sci-Fi' },
  { y:null, t:'Ice Station Zebra', a:'Alistair MacLean', g:'Thriller' },
  { y:null, t:'The Guns of Navarone', a:'Alistair MacLean', g:'Thriller' },
  { y:null, t:'Dune', a:'Frank Herbert', g:'Sci-Fi' },
  { y:null, t:'Dune Messiah', a:'Frank Herbert', g:'Sci-Fi' },
  { y:null, t:'The Sheep Look Up', a:'John Brunner', g:'Sci-Fi' },
  { y:null, t:'Flowers for Algernon', a:'Daniel Keyes', g:'Sci-Fi' },
  { y:null, t:'Birch Bark Canoe', a:'', g:'Other' },
  { y:null, t:'The Glass House', a:'', g:'Fiction' },
  { y:null, t:'Shogun', a:'James Clavell', g:'Historical Fiction' },
  { y:null, t:'Stranger in a Strange Land', a:'Robert Heinlein', g:'Sci-Fi' },
  { y:null, t:'Starship Troopers', a:'Robert Heinlein', g:'Sci-Fi' },
  { y:null, t:'Glory Road', a:'Robert Heinlein', g:'Sci-Fi' },
  { y:null, t:'I Will Fear No Evil', a:'Robert Heinlein', g:'Sci-Fi' },
  { y:null, t:'The Martian Chronicles', a:'Ray Bradbury', g:'Sci-Fi' },
  { y:null, t:'The World of Null-A', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'Slan', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'The War Against the Rull', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'Voyage of the Space Beagle', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'The Book of Ptath', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:'The Darkness on Diamondia', a:'A. E. Van Vogt', g:'Sci-Fi' },
  { y:null, t:"Salem's Lot", a:'Stephen King', g:'Horror' },
  { y:null, t:'The Pnume', a:'Jack Vance', g:'Sci-Fi' },
  { y:null, t:'The Wankh', a:'Jack Vance', g:'Sci-Fi' },
  { y:null, t:'The Chasch', a:'Jack Vance', g:'Sci-Fi' },
  { y:null, t:'The Dirdir', a:'Jack Vance', g:'Sci-Fi' },
  { y:null, t:'A Boy and His Dog', a:'Harlan Ellison', g:'Sci-Fi' },
  { y:null, t:'Lord of the Flies', a:'William Golding', g:'Fiction' },
  { y:null, t:'The Catcher in the Rye', a:'J. D. Salinger', g:'Fiction' },
  { y:null, t:'Of Mice and Men', a:'John Steinbeck', g:'Fiction' },
  { y:null, t:'The Old Man and the Sea', a:'Ernest Hemingway', g:'Fiction' },
  { y:null, t:'A Snake in the Grass', a:'', g:'Other' },
];

function esc(s) { return (s || '').replace(/'/g, "''"); }

const rows = books.map(b => {
  const bid = nextId();
  const date = b.y ? `'${b.y}-01-01'` : 'null';
  return `('${USER_ID}', '${bid}', '${esc(b.t)}', '${esc(b.a)}', '${b.g}', 'Read', 0, 0, null, null, null, ${date}, null, null, 0, null, null, null)`;
});

const sql = `INSERT INTO books (user_id, book_id, title, author, genre, shelf, rating, pages, cover_url, cover_id, isbn, date, scores, description, current_page, liked_aspects, disliked_aspects, notes)\nVALUES\n${rows.join(',\n')};`;

require('fs').writeFileSync('scripts/import.sql', sql);
console.log(`Generated ${books.length} rows → scripts/import.sql`);
